[package]
name = "ktls"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hapsoc/ktls"
documentation = "https://docs.rs/ktls"
readme = "README.md"
description = """
Configures kTLS for tokio-rustls client and server connections.
"""

[dependencies]
libc = "0.2.133"
thiserror = "1.0.37"
tracing = "0.1.36"
tokio-rustls = "0.23.4"
rustls = { version = "0.20.6", features = ["secret_extraction"] }
smallvec = "1.10.0"
memoffset = "0.6.5"
pin-project-lite = "0.2.9"
tokio = { version = "1.21.2", features = ["net", "macros"] }
futures = "0.3.24"

[dependencies.ktls-sys]
git = "https://github.com/hapsoc/ktls-sys"
rev = "798466d"

[patch.crates-io]
# rustls = { path = "../rustls/rustls" }
rustls = { git = "https://github.com/rustls/rustls", rev = "a981f0914eb517788a09f3e764fe64f527e0181e" }

[dev-dependencies]
rcgen = "0.10.0"
socket2 = "0.4.7"
tokio = { version = "1.21.2", features = ["full"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
